name: My first action

on:
  # push 到 master 分支時會觸發
  push:
    branches:
    - master

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    container:
      image: cymetricsdev.azurecr.io/security/zap-scard
      credentials:
        username: fd43f06b-6880-4d16-a32e-5b240e5568c7
        password: CuF572Epmm_~MGUzn5XsOQAl780_YOcK_N
    steps:
    - name: first action
      run: |
        ls -l