name: My first action

on:
  # push 到 master 分支時會觸發
  push:
    branches:
    - master

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    container:
      image: cymetricsdev.azurecr.io/security/email-auth
      credentials:
        username: fd43f06b-6880-4d16-a32e-5b240e5568c7
        password: ${{ secrets.PWD }}
    steps:
    - name: first action
      run: |
        echo $HIO
        echo $GITHUB_REF